apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calling-kubectl-using-python
subjects:
  - kind: ServiceAccount
    name: calling-kubectl-using-python
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
