apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calling-kubectl-using-python
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - delete
